### ISSUE TITLE
error

### ISSUE THREAD

**Issue by aryoow** [HerrEurobeat/steam-comment-service-bot#12]
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: InvalidPassword
    at SteamUser.<anonymous> (/home/ubuntu/environment/steam-comment-service-bot/node_modules/steam-user/components/logon.js:468:16)
    at handlers.forEach (/home/ubuntu/environment/steam-comment-service-bot/node_modules/steam-user/components/classes/HandlerManager.js:37:12)
    at Array.forEach (<anonymous>)
    at HandlerManager.emit (/home/ubuntu/environment/steam-comment-service-bot/node_modules/steam-user/components/classes/HandlerManager.js:36:12)
    at SteamUser._handleMessage (/home/ubuntu/environment/steam-comment-service-bot/node_modules/steam-user/components/messages.js:545:24)
    at SteamUser._handleNetMessage (/home/ubuntu/environment/steam-comment-service-bot/node_modules/steam-user/components/messages.js:480:7)
    at SteamUser.processMulti (/home/ubuntu/environment/steam-comment-service-bot/node_modules/steam-user/components/messages.js:572:9)
    at SteamUser.<anonymous> (/home/ubuntu/environment/steam-comment-service-bot/node_modules/steam-user/components/messages.js:566:16)
    at handlers.forEach (/home/ubuntu/environment/steam-comment-service-bot/node_modules/steam-user/components/classes/HandlerManager.js:37:12)
    at Array.forEach (<anonymous>)
Emitted 'error' event at:
    at SteamUser.<anonymous> (/home/ubuntu/environment/steam-comment-service-bot/node_modules/steam-user/components/logon.js:471:9)
    at handlers.forEach (/home/ubuntu/environment/steam-comment-service-bot/node_modules/steam-user/components/classes/HandlerManager.js:37:12)
    [... lines matching original stack trace ...]
    at Array.forEach (<anonymous>)

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue.
Can you give any more information? Judging the error, it seems like the password you have provided for one of the accounts in logininfo.json is wrong.
