### ISSUE TITLE
Beta Version Bug

### ISSUE THREAD

**Issue by Ecstasyyy1337** [HerrEurobeat/steam-comment-service-bot#127]
This is all the console log while I only executed `npm install` and no other command, it just won't start

> [2022-04-19 00:48:31 | INFO] Starting process...

Bootup sequence started...
---------------------------------------------------------
[2022-04-19 00:48:31 | INFO] Importing cache.json...
[2022-04-19 00:48:31 | INFO] Importing data.json...
[2022-04-19 00:48:31 | INFO] Importing config.json...
[2022-04-19 00:48:31 | INFO] Importing advancedconfig.json...
[2022-04-19 00:48:31 | INFO] Accounts.txt does exist and is not empty - using it instead of logininfo.json.
[2022-04-19 00:48:31 | INFO] Loading lastcomment.db database...
[2022-04-19 00:48:31 | INFO] steam-comment-service-bot made by 3urobeat version BETA 2.12 b6
[2022-04-19 00:48:31 | INFO] Using node.js version v16.13.0...
[2022-04-19 00:48:31 | INFO] Running on win32...
[2022-04-19 00:48:31 | INFO] Using beta-testing branch | firststart is true | This is start number 1
[Notice] Your updater and bot is running in beta mode. These versions are often unfinished and can be unstable.
         If you would like to switch, open data.json and change 'beta-testing' to 'master'.
         If you find an error or bug please report it: https://github.com/HerrEurobeat/steam-comment-service-bot/issues/new/choose

[2022-04-19 00:48:31 | INFO] Refreshing ownerids in cache.json...
[2022-04-19 00:48:31 | INFO] Checking config for 3urobeat's leftovers...
[2022-04-19 00:48:31 | INFO] Checking for invalid config values...
[INFO] Your maxOwnerComments value in config.json can't be smaller than 1! Automatically setting it to 1...
[2022-04-19 00:48:31 | INFO] Checking if owner link is valid...
[2022-04-19 00:48:31 | INFO] Comment config values: commentdelay = 15000 | maxCommentsOverall = 1 | randomizeAcc = false
[INFO] Running compatibility feature 21200.js...

[WARN] advancedconfig.json seems to have lost it's data/is corrupted. Trying to restore from backup...
[WARN] Backup seems to be broken/not available! Pulling file from GitHub...
[2022-04-19 00:48:31 | INFO] Pulling: https://raw.githubusercontent.com/HerrEurobeat/steam-comment-service-bot/beta-testing/advancedconfig.json
[2022-04-19 00:48:31 | INFO] Successfully checked owner link. steamID64: 76561198890284474
[INFO] Successfully pulled new advancedconfig.json from GitHub.

[2022-04-19 00:48:31 | INFO] Accounts.txt does exist and is not empty - using it instead of logininfo.json.
[2022-04-19 00:48:31 | INFO] Loading lastcomment.db database...
[2022-04-19 00:48:31 | INFO] steam-comment-service-bot made by 3urobeat version BETA 2.12 b6
[2022-04-19 00:48:31 | INFO] Using node.js version v16.13.0...
[2022-04-19 00:48:31 | INFO] Running on win32...
[2022-04-19 00:48:31 | INFO] Using beta-testing branch | firststart is true | This is start number 1
[Notice] Your updater and bot is running in beta mode. These versions are often unfinished and can be unstable.
         If you would like to switch, open data.json and change 'beta-testing' to 'master'.
         If you find an error or bug please report it: https://github.com/HerrEurobeat/steam-comment-service-bot/issues/new/choose

[2022-04-19 00:48:31 | INFO] Refreshing ownerids in cache.json...
[2022-04-19 00:48:31 | INFO] Checking config for 3urobeat's leftovers...
[2022-04-19 00:48:31 | INFO] Checking for invalid config values...
[2022-04-19 00:48:31 | INFO] Checking if owner link is valid...
[2022-04-19 00:48:31 | INFO] Comment config values: commentdelay = 15000 | maxCommentsOverall = 1 | randomizeAcc = false
[INFO] Running compatibility feature 21200.js...
[ERROR] Uncaught Exception Error! Reason: TypeError: Cannot read properties of undefined (reading 'globalcommentcooldown')
    at Object.module.exports.run (C:\Users\mihai\Desktop\steam-comment-service-bot-beta-testing\src\updater\compatibility\21200.js:23:26)
    at C:\Users\mihai\Desktop\steam-comment-service-bot-beta-testing\src\updater\updater.js:164:18
    at Object.module.exports.checkAndGetFile (C:\Users\mihai\Desktop\steam-comment-service-bot-beta-testing\src\starter.js:274:18)
    at runCompFeature (C:\Users\mihai\Desktop\steam-comment-service-bot-beta-testing\src\updater\updater.js:161:17)
    at Object.module.exports.compatibility (C:\Users\mihai\Desktop\steam-comment-service-bot-beta-testing\src\updater\updater.js:195:9)
    at C:\Users\mihai\Desktop\steam-comment-service-bot-beta-testing\src\controller\controller.js:180:49
    at Object.module.exports.checkAndGetFile (C:\Users\mihai\Desktop\steam-comment-service-bot-beta-testing\src\starter.js:274:18)
    at C:\Users\mihai\Desktop\steam-comment-service-bot-beta-testing\src\controller\controller.js:178:45
    at Object.module.exports.run (C:\Users\mihai\Desktop\steam-comment-service-bot-beta-testing\src\controller\helpers\datacheck.js:154:5)
    at C:\Users\mihai\Desktop\steam-comment-service-bot-beta-testing\src\controller\controller.js:170:43

[2022-04-19 00:48:31 | WARN] If the bot doesn't work correctly anymore after this error then please restart it!
[2022-04-19 00:48:32 | INFO] Successfully checked owner link. steamID64: 76561198890284474
[2022-04-19 00:53:31 | INFO] Checking for update in beta-testing branch...
[2022-04-19 00:53:31 | INFO] No available update found. (online: BETA 2.12 b6 | local: BETA 2.12 b6)

**Comment by HerrEurobeat** [comment]
Hm, looks like the compatibility feature is failing to find one of the new keys in the config.  
Not sure why, will look into it though. Thanks for reporting!

**Comment by HerrEurobeat** [comment]
Should be fixed now.  
Issue happened when bot was started for the first time and so no `configjson` entry existed in the `cache.json` file from a previous start.  
  
Closing as this issue doesn't affect the master branch.
