### ISSUE TITLE
Please help, logininfo.json

### ISSUE THREAD

**Issue by Maytrix64** [HerrEurobeat/steam-comment-service-bot#24]
Hi all, I've been having this issue ever since the update.
Whenever I start the bot I get prompted with:

SyntaxError: C:\Users\Maytix\Desktop\steam-comment-service-bot-master\logininfo.json: Unexpected string in JSON at position 125
    at parse (<anonymous>)
[90m    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1219:22)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:1034:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:923:14)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:1074:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:72:18)[39m
    at Object.<anonymous> (C:\Users\Maytrix\Desktop\steam-comment-service-bot-master\src\controller.js:6:19)
[90m    at Module._compile (internal/modules/cjs/loader.js:1185:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:1034:32)[39m

Open to all suggestions xD

**Comment by HerrEurobeat** [comment]
Hi, thanks for opening an issue!
It seems like your `logininfo.json` got a bit corrupted.  
Please make sure your logininfo follows the same pattern like the default one in this repository or if you don't have that many accounts just redownload the one file and fill in your login informations again.
Let me know if that fixed it.

**Comment by Maytrix64** [comment]
> Hi, thanks for opening an issue!
> It seems like your `logininfo.json` got a bit corrupted.
> Please make sure your logininfo follows the same pattern like the default one in this repository or if you don't have that many accounts just redownload the one file and fill in your login informations again.
> Let me know if that fixed it.

Yeah your right, the login file was corrupt. However when I tried getting the bots to comment it came up with:

C:\Users\Maytrix\Desktop\steam-comment-service-bot-master\src\bot.js:153
            if ((Date.now() - lastcomment[lastcommentsteamID].time) < (config.commentcooldown * 60000)) { //check if user has cooldown applied
                                                              ^

TypeError: Cannot read property 'time' of undefined
    at SteamUser.<anonymous> (C:\Users\Maytrix\Desktop\steam-comment-service-bot-master\src\bot.js:153:63)
    at SteamUser.emit (events.js:315:20)
    at SteamUser._emitIdEvent (C:\Users\Maytrix\Desktop\steam-comment-service-bot-master\node_modules\steam-user\components\utility.js:28:12)
    at SteamUser.<anonymous> (C:\Users\Maytrix\Desktop\steam-comment-service-bot-master\node_modules\steam-user\components\chatroom.js:56:8)
    at C:\Users\Maytrix\Desktop\steam-comment-service-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:37:12
    at Array.forEach (<anonymous>)
    at HandlerManager.emit (C:\Users\Maytrix\Desktop\steam-comment-service-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:36:12)
    at SteamUser._handleMessage (C:\Users\Maytrix\Desktop\steam-comment-service-bot-master\node_modules\steam-user\components\messages.js:545:24)
    at SteamUser._handleNetMessage (C:\Users\Maytrix\Desktop\steam-comment-service-bot-master\node_modules\steam-user\components\messages.js:480:7)
    at SteamUser.processMulti (C:\Users\Maytix\Desktop\steam-comment-service-bot-master\node_modules\steam-user\components\messages.js:572:9)
