### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by anuranjan930** [HerrEurobeat/steam-comment-service-bot#42]
**Describe the bug**
i started the script by typing node start.js 
**Full error**
this is the error that i've got 

PS C:\Users\choswiz\Desktop\steam-comment-service-bot-master> node start.js
internal/modules/cjs/loader.js:1175
    throw err;
    ^

SyntaxError: C:\Users\choswiz\Desktop\steam-comment-service-bot-master\logininfo.json: Unexpected string in JSON at position 168
    at parse (<anonymous>)
[90m    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1172:22)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:986:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:879:14)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:1026:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:72:18)[39m
    at Object.<anonymous> (C:\Users\choswiz\Desktop\steam-comment-service-bot-master\src\controller.js:6:19)
[90m    at Module._compile (internal/modules/cjs/loader.js:1138:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:986:32)[39m

**Additional context**
there's nothing else that's imp ig idk

thank you

**Comment by anuranjan930** [comment]
actually this has been fixed but now i am getting invalid password error
