### ISSUE TITLE
invalidpassword

### ISSUE THREAD

**Issue by anuranjan930** [HerrEurobeat/steam-comment-service-bot#43]
**Describe the bug**
i started the script and it said you have to wait 8 seconds then 
then i got this error:
**Full error**
PS C:\Users\choswiz\Desktop\steam-comment-service-bot-master> node start.js

[2020-06-14 19:40:46] What's new: Fixed bot corrupting the config and crashing on restart due to simultaneous writes.
[2020-06-14 19:40:46] Logging in... Estimated wait time: 8 seconds.
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: InvalidPassword
    at SteamUser.<anonymous> (C:\Users\choswiz\Desktop\steam-comment-service-bot-master\node_modules\steam-user\components\logon.js:468:16)
    at C:\Users\choswiz\Desktop\steam-comment-service-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:37:12
    at Array.forEach (<anonymous>)
    at HandlerManager.emit (C:\Users\choswiz\Desktop\steam-comment-service-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:36:12)
    at SteamUser._handleMessage (C:\Users\choswiz\Desktop\steam-comment-service-bot-master\node_modules\steam-user\components\messages.js:545:24)
    at SteamUser._handleNetMessage (C:\Users\choswiz\Desktop\steam-comment-service-bot-master\node_modules\steam-user\components\messages.js:480:7)
    at SteamUser.processMulti (C:\Users\choswiz\Desktop\steam-comment-service-bot-master\node_modules\steam-user\components\messages.js:572:9)
    at SteamUser.<anonymous> (C:\Users\choswiz\Desktop\steam-comment-service-bot-master\node_modules\steam-user\components\messages.js:566:16)
    at C:\Users\choswiz\Desktop\steam-comment-service-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:37:12
    at Array.forEach (<anonymous>)
Emitted 'error' event on SteamUser instance at:
    at SteamUser.<anonymous> (C:\Users\choswiz\Desktop\steam-comment-service-bot-master\node_modules\steam-user\components\logon.js:471:9)
    at C:\Users\choswiz\Desktop\steam-comment-service-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:37:12
    [... lines matching original stack trace ...]
    at Array.forEach (<anonymous>) {
  eresult: 5
}

**Additional context**
thanks for helping mate i really appreciate your work

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue!
Please make sure that your `logininfo.json` follows exactly this pattern:
```
{
	"bot0": ["username0", "password0"],
	"bot1": ["username1", "password1"],
	"bot2": ["username2", "password2"]
}
```
Your usernames and passwords need to be inside the quotes (`"`). Please make sure this is the case and that your passwords are correct.

**Comment by HerrEurobeat** [comment]
Hey, did you manage to fix the error?

**Comment by HerrEurobeat** [comment]
Since you didn't reply I assume that it is working now.
If this problem is still present, feel free to just comment again.
If you encounter another problem/error/bug, please open another issue.
Thanks!
