### ISSUE TITLE
Help Me Please to fix this error (Invalid Password)

### ISSUE THREAD

**Issue by yohanneslex** [HerrEurobeat/steam-comment-service-bot#45]
Error: InvalidPassword
    at SteamUser.<anonymous> (D:\Download\steam-comment-service-bot-master\steam-comment-service-bot-master\node_modules\steam-user\components\logon.js:468:16)
    at D:\Download\steam-comment-service-bot-master\steam-comment-service-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:37:12
    at Array.forEach (<anonymous>)
    at HandlerManager.emit (D:\Download\steam-comment-service-bot-master\steam-comment-service-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:36:12)
    at SteamUser._handleMessage (D:\Download\steam-comment-service-bot-master\steam-comment-service-bot-master\node_modules\steam-user\components\messages.js:545:24)
    at SteamUser._handleNetMessage (D:\Download\steam-comment-service-bot-master\steam-comment-service-bot-master\node_modules\steam-user\components\messages.js:480:7)
    at SteamUser.processMulti (D:\Download\steam-comment-service-bot-master\steam-comment-service-bot-master\node_modules\steam-user\components\messages.js:572:9)
    at SteamUser.<anonymous> (D:\Download\steam-comment-service-bot-master\steam-comment-service-bot-master\node_modules\steam-user\components\messages.js:566:16)
    at D:\Download\steam-comment-service-bot-master\steam-comment-service-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:37:12
    at Array.forEach (<anonymous>)
Emitted 'error' event on SteamUser instance at:
    at SteamUser.<anonymous> (D:\Download\steam-comment-service-bot-master\steam-comment-service-bot-master\node_modules\steam-user\components\logon.js:471:9)
    at D:\Download\steam-comment-service-bot-master\steam-comment-service-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:37:12
    [... lines matching original stack trace ...]
    at Array.forEach (<anonymous>) {
  eresult: 5
}

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue!
Please make sure that your `logininfo.json` follows exactly this pattern:
```
{
	"bot0": ["username0", "password0"],
	"bot1": ["username1", "password1"],
	"bot2": ["username2", "password2"]
}
```
Your usernames and passwords need to be inside the quotes ("). Please make sure this is the case and that your passwords are correct.

**Comment by HerrEurobeat** [comment]
Since you didn't reply I assume that it is working for you now.
If this problem is still present, feel free to just comment again.
If you encounter another problem/error/bug, please open another issue.
Thanks!
