### ISSUE TITLE
Stupid bootup limited checker crashes the bot from time to time (🖕)

### ISSUE THREAD

**Issue by HerrEurobeat** [HerrEurobeat/steam-comment-service-bot#49]
**Describe the bug**
How many accounts are limited checker is broken and constantly crashes the bot if it is in the mood for it.

**Full error**
```
H:\Sonstiges\Steam\Steam Bots\steam-comment-service-bot\src\controller.js:324
    if (Object.keys(communityobject).length == (Object.keys(logininfo).length - updater.skippedaccounts.length) && botobject[Object.keys(botobject).length - 1].limitations != undefined && module.exports.accisloggedin == true) {      
                                                                                                                                                                ^

TypeError: Cannot read property 'limitations' of undefined
    at Timeout._onTimeout (H:\Sonstiges\Steam\Steam Bots\steam-comment-service-bot\src\controller.js:324:161)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

**Additional context**
Please add any other information here if you have some.
Seriously fuck that check. I get agression seeing it.

**Comment by HerrEurobeat** [comment]
Fixed in commit 8adc902 (Version 2.7.2).
