### ISSUE TITLE
idk

### ISSUE THREAD

**Issue by sergiubaba** [HerrEurobeat/steam-comment-service-bot#52]
**Error/Element that doesn't work**
Please include the full error you get or if you get none, describe precisely what happened.

**Additional information**
Please add any other information here if you have some.

SyntaxError: C:\Users\sergi\Desktop\steam-comment-service-bot-master\logininfo.json: Unexpected string in JSON at position 55
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:961:27)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (C:\Users\sergi\Desktop\steam-comment-service-bot-master\src\controller.js:12:17)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)

**Comment by HerrEurobeat** [comment]
Hi, thanks for opening an issue.
It seems like you have a syntax error in your logininfo.json.
Please make sure your logininfo.json follows exactly this format:
```
{
	"bot0": ["username0", "password0"],
	"bot1": ["username1", "password1"],
	"bot2": ["username2", "password2"]
}
```
Make sure that after every line is a comma but not on the last line. (like in the example above)

**Comment by sergiubaba** [comment]
> Hi, thanks for opening an issue.
> It seems like you have a syntax error in your logininfo.json.
> Please make sure your logininfo.json follows exactly this format:
> 
> ```
> {
> 	"bot0": ["username0", "password0"],
> 	"bot1": ["username1", "password1"],
> 	"bot2": ["username2", "password2"]
> }
> ```
> 
> Make sure that after every line is a comma but not on the last line. (like in the example above)

thanks i solved that
